
@odata = http://localhost:4005/odata/v4/admin
@rest = http://localhost:4005/rest/data
@hcql = http://localhost:4005/hcql/data

@cql = \n Content-Type: text/plain \n\n


GET {{odata}}
###

GET {{odata}}/$metadata
###

GET {{odata}}/Connections
###

POST {{odata}}/Flights
Authorization: Basic alice:
Content-Type: application/json

{
  "aircraft": "A380-800",
  "currency_code": "USD",
  "date": "2024-06-06",
  "flight_ID": "TEST001",
  "maximum_seats": 475,
  "occupied_seats": 446,
  "price": "3781.0000"
}
###

GET {{rest}}/Connections
###

GET {{hcql}}/Connections { ID, airline.name, departure.name, destination.name }
###

GET {{hcql}}/Connections
Content-Type: text/plain

{
  ID,
  airline.name,
  departure.name,
  destination.name
}
###

GET {{hcql}}/Connections {{cql}} {
  code,
  departure.name as ![from],
  destination.name as ![to],
  airline.name as ![by],
}
###

GET {{hcql}}/Flights
###

GET {{hcql}}/Flights {{cql}} {
  connection {
    code as flight,
    departure.name as ![from],
    destination.name as ![to],
    airline.name as ![by],
  },
  price, currency.name as ![currency],
  flightDate as ![date],
  freeSeats as ![free seats],
}
###

GET {{hcql}}/Flights {{cql}} {
  connection.code as flight,
  connection.departure.name as ![from],
  connection.destination.name as ![to],
  connection.airline.name as ![by],
  flightDate as ![date],
  connection.departureTime as ![departure],
  connection.arrivalTime as ![arrival],
}
###

POST {{hcql}}
Accept: application/octet-stream{{cql}} SELECT FROM $OData {
  '$metadata#Flights' as ![@odata.context],
  count(Flights.ID,Flights.date) as ![@odata.count],
  Flights[order by ID limit 30 offset 0] as value {
    ID,
    date,
    aircraft,
    price,
    currency_code,
    free_seats,
    departure,
    arrival,
    distance,
  },
}
###

POST {{hcql}}
Accept: application/octet-stream
Content-Type: application/json

{"SELECT":{
  "one": true,
  "from":{"ref":["$OData"]},
  "columns":[
    {"val":"$metadata#Flights","as":"@odata.context"},
    {"func":"count","args":[{"ref":["Flights","ID"]},{"ref":["Flights","date"]}],"as":"@odata.count"},
    {"ref":[
      {
        "id":"Flights",
        "orderBy":[{"ref":["ID"]}],
        "limit":{"rows":{"val":30},"offset":{"val":0}}
      }],
      "expand":[
        {"ref":["ID"]},
        {"ref":["date"]},
        {"ref":["aircraft"]},
        {"ref":["price"]},
        {"ref":["currency_code"]},
        {"ref":["free_seats"]},
        {"ref":["departure"]},
        {"ref":["arrival"]},
        {"ref":["distance"]}
      ],
      "as":"value"
    }
  ]
}}
###

POST {{hcql}}
Accept: application/octet-stream
Content-Type: application/json

{"SELECT":{
  "one": true,
  "from":{"ref":[
    "$OData",
    {
      "id":"Flights",
      "where":[{"ref":["ID"]},"=",{"val":"EA0018"},"and",{"ref":["date"]},"=",{"val":"2024-06-06"}]
    }
  ]},
  "columns": [
    {"val":"$metadata#Flights/$entity","as":"@odata.context"},
    {"ref":["ID"]},
    {"ref":["date"]},
    {"ref":["aircraft"]},
    {"ref":["price"]},
    {"ref":["currency_code"]},
    {"ref":["free_seats"]},
    {"ref":["departure"]},
    {"ref":["arrival"]},
    {"ref":["distance"]}
  ]
}}
###